blank_issues_enabled: false
contact_links:
  - name: 🔥 Merchant API support
    url: https://support.google.com/merchants/contact/shopping_api_support_form
    about: If you want to raise an issue/feedback or you need support on the Merchant API Code Samples
